City.find_or_create_by(name: "ABAIARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ABILIO MARTINS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ACARAPE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ACARAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ACOPIARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ADRIANOPOLIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AGUA VERDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AGUAI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AIUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AIUABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ALAGOINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ALCANTARAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ALGODOES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ALMOFALA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ALTANEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ALTO SANTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMANAIARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMANARI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMANIUTUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMARELAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMARO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMERICA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AMONTADA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANAUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANINGAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANJINHOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANTONINA DO NORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANTONIO BEZERRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANTONIO DIOGO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ANTONIO MARQUES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "APRAZIVEL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "APUIARES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AQUINOPOLIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AQUIRAZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARACAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARACATI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARACATIACU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARACATIARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARACOIABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARAJARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARANAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARAPA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARAPARI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARAPORANGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARAQUEM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARARENDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARARIPE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARARIUS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARATAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARATICUM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARATUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AREIAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARISCOS DOS MARIANOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARNEIROZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AROEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARROJADO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ARUARU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ASSARE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ASSUNCAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "AURORA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BAIXA GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BAIXIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BAIXIO DA DONANA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BANABUIU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BANDEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARAO DE AQUIRAZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARBALHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARRA DO SOTERO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARRA NOVA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARREIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARREIRA DOS VIANAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARREIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARREIROS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARRENTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARRO ALTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BARROQUINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BATURITE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BEBERIBE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BELA CRUZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BELA VISTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BETANIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BITUPITA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BIXOPA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BOA AGUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BOA ESPERANCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BOA VIAGEM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BOA VISTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BOA VISTA DO CAXITORE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BONFIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BONHU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BONITO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BORGES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BREJINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BREJO GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BREJO SANTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BROTAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BURITIZAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "BURITIZINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CABREIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CACHOEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CACHOEIRA GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAICARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAICARINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAIO PRADO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAIOCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAIPU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CALABACA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CALDEIRAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CALIFORNIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMBOAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMILOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMOCIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMPANARIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMPESTRE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAMPOS SALES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CANAAN".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CANAFISTULA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CANGATI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CANINDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CANINDEZINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAPISTRANO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAPONGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAPONGA DA BERNARDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARACARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARIDADE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARIRE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARIRIACU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARIUS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARIUTABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARMELOPOLIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARNAUBAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARNAUBAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARNAUBINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARQUEJO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARRAPATEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARUATAI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARVALHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CARVOEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CASCAVEL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CASTANHAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CATARINA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CATOLE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CATUANA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CATUNDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAUCAIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CAXITORE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CEDRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CEMOABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CHAVAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CHORO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CHOROZINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CIPO DOS ANJOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "COCOCI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CODIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "COITE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "COLINA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CONCEICAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "COREAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CORREGO DOS FERNANDES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRATEUS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRATO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRIOULOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRISTAIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CROATA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRUXATI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRUZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRUZ DE PEDRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CRUZEIRINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CUNCAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CURATIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CURUPIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "CUSTODIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DANIEL DE QUEIROS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DELMIRO GOUVEIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DEPUTADO IRAPUAN PINHEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DESERTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DOM LEME".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DOM MAURICIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DOM QUINTINO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DOMINGOS DA COSTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DONATO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "DOURADOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "EBRON".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "EMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "EMATUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ENCANTADO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ENGENHEIRO JOAO TOME".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ENGENHEIRO JOSE LOPES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ENGENHO VELHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ERERE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ESPACINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ESPERANCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ESPINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "EUSEBIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FARIAS BRITO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FATIMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FEITICEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FEITOSA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FELIZARDO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FLAMENGO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FLORES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FORQUILHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FORTALEZA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FORTIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "FRECHEIRINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GADO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GADO DOS RODRIGUES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GAMELEIRA DE SAO SEBASTIAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GARCAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GAZEA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GENERAL SAMPAIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GENERAL TIBURCIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GENIPAPEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GERERAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GIQUI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GIRAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GRACA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GRANJA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GRANJEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GROAIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUAIUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUAJIRU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUANACES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUARACIABA DO NORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUARAMIRANGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUARARU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUASSI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUASSOSSE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GUIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "GURIU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "HIDROLANDIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "HOLANDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "HORIZONTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IAPI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBARETAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBIAPABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBIAPINA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBICATU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBICUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBICUITABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBICUITINGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBOREPI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBUACU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IBUGUACU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ICAPUI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ICARAI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ICO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ICOZINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IDEAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IGAROI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IGUATU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "INDEPENDENCIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "INGAZEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "INHAMUNS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "INHUCU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "INHUPORANGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IPAPORANGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IPAUMIRIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IPU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IPUEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IPUEIRAS DOS GOMES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IRACEMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IRAJA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IRAPUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IRATINGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "IRAUCUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ISIDORO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITACIMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAGUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAICABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAIPABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAITINGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITANS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAPAGE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAPEBUSSU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAPEIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAPIPOCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAPIUNA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAPO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITAREMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ITATIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JABURUNA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JACAMPARI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JACARECOARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JACAUNA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAGUARAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAGUARETAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAGUARIBARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAGUARIBE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAGUARUANA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAIBARAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JAMACARU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JANDRANGOEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JARDIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JARDIMIRIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JATI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JIJOCA DE JERICOACOARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JOAO CORDEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JORDAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JOSE DE ALENCAR".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUATAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUAZEIRO DE BAIXO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUAZEIRO DO NORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUBAIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUCAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUREMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "JUSTINIANO SERPA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LACERDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LADEIRA GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAGOA DE SAO JOSE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAGOA DO JUVENAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAGOA DO MATO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAGOA DOS CRIOULOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAGOINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAMBEDOURO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAMEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LAVRAS DA MANGABEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LIMA CAMPOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LIMOEIRO DO NORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LISIEUX".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LIVRAMENTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "LOGRADOURO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MACAMBIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MACAOCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MACARAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MACEIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MADALENA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MAJOR SIMPLICIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MAJORLANDIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MALHADA GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MANIBU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MANITUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MAPUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARACANAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARANGUAPE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARARUPA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARCO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARINHEIROS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARRECAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARROCOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARRUAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MARTINOPOLE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MASSAPE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MATA FRESCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MATIAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MATRIZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MAURITI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MEL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MERUOCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MIGUEL XAVIER".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MILAGRES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MILHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MILTON BELO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MINEIROLANDIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MIRAGEM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MIRAIMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MIRAMBE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MISSAO NOVA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MISSAO VELHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MISSI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MOITAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MOMBACA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONGUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONSENHOR TABOSA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONTE ALEGRE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONTE CASTELO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONTE GRAVE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONTE SION".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MONTENEBO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MORADA NOVA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MORAUJO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MORRINHOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MORRINHOS NOVOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MORRO BRANCO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MUCAMBO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MULUNGU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MUMBABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MUNDAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MURIBECA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MURITI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "MUTAMBEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NARANIU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NASCENTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NENENLANDIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOSSA SENHORA DO LIVRAMENTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVA BETANIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVA FATIMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVA FLORESTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVA OLINDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVA RUSSAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVA VIDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVO ASSIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "NOVO ORIENTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "OCARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "OITICICA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "OLHO-D'AGUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "OLHO-D'AGUA DA BICA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "OLIVEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "OROS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PACAJUS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PACATUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PACOTI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PACUJA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PADRE CICERO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PADRE LINHARES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PADRE VIEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PAJEU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PAJUCARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PALESTINA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PALESTINA DO NORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PALHANO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PALMACIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PALMATORIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PANACUI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARACUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARACURU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARAIPABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARAJURU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARAMBU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARAMOTI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARANGABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARAPUI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARAZINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PARIPUEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PASSAGEM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PASSAGEM FUNDA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PASTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PATACAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PATRIARCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PAVUNA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PECEM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PEDRA BRANCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PEDRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PEDRINHAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PEIXE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PEIXE GORDO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PENAFORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PENTECOSTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PEREIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PERNAMBUQUINHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PESSOA ANTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PINDOGUABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PINDORETAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PIO X".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PIQUET CARNEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PIRABIBU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PIRANGI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PIRES FERREIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PITOMBEIRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PITOMBEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PLACIDO MARTINS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "POCO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "POCO COMPRIDO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "POCO GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PODIMIRIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PONTA DA SERRA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PORANGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PORFIRIO SAMPAIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PORTEIRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "POTENGI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "POTI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "POTIRETAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PRATA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "PRUDENTE DE MORAIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUATIGUABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUEIMADAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIMAMI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUINCOE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUINCUNCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUITAIUS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUITERIANOPOLIS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIXADA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIXARIU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIXELO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIXERAMOBIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIXERE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "QUIXOA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RAIMUNDO MARTINS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "REDENCAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RERIUTABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RIACHAO DO BANABUIU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RIACHO GRANDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RIACHO VERDE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RIACHO VERMELHO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RINARE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "ROLDAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "RUSSAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SABIAGUABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SABOEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SACRAMENTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SALAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SALITRE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAMBAIBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTA ANA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTA FE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTA FELICIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTA LUZIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTA QUITERIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTA TEREZA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTANA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTANA DO ACARAU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTANA DO CARIRI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTAREM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTO ANTONIO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTO ANTONIO DA PINDOBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SANTO ANTONIO DOS FERNANDES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO BARTOLOMEU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO BENEDITO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO DOMINGOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO FELIPE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO FRANCISCO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO GERARDO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO GONCALO DO AMARANTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO GONCALO DO UMARI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOAO DE DEUS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOAO DO JAGUARIBE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOAO DOS QUEIROZ".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOAQUIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOAQUIM DO SALGADO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOSE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOSE DAS LONTRAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOSE DE SOLONOPOLE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO JOSE DO TORTO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO LUIS DO CURU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO MIGUEL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO PAULO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO PEDRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO ROMAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO SEBASTIAO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAO VICENTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAPO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SAPUPARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SEBASTIAO DE ABREU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SENADOR CARLOS JEREISSATI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SENADOR POMPEU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SENADOR SA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SERENO DE CIMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SERRA DO FELIX".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SERRAGEM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SERROTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SERROTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SITIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SITIOS NOVOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SIUPE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SOBRAL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SOLEDADE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SOLONOPOLE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SUASSURANA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SUCATINGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SUCESSO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "SUSSUANHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TABAINHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TABOLEIRO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TABULEIRO DO NORTE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TAIBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TAMBORIL".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TANQUES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TAPERA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TAPERUABA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TAPUIARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TARGINOS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TARRAFAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TAUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TEJUCUOCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TIANGUA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TIMONHA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TIPI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TOME".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TRAIRI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TRAPIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TRICI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TROIA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TRUSSU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TUCUNDUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TUCUNS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TUINA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "TURURU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UBAJARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UBAUNA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UBIRACU".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UIRAPONGA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UMARI".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UMARITUBA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UMBURANAS".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "UMIRIM".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "URUBURETAMA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "URUOCA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "URUQUE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VARJOTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VARZEA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VARZEA ALEGRE".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VARZEA DA VOLTA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VARZEA DO GILO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VAZANTES".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VENTURA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VERTENTES DO LAGEDO".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VICOSA DO CEARA".sem_acento.mb_chars.upcase)
City.find_or_create_by(name: "VILA SOARES".sem_acento.mb_chars.upcase)
